apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-secret
  namespace: default
spec:
  encryptedData:
    password: AgBqCD6dnXl5bz/sTgXOTbuL8cQt5PNd/tqLDL/RCD/D/m+yOOeV+gzr3IohrssrQP/WNQZdm/THKDIYgv3HedMIxupMfbEZ537wXKKnQAK7TIrQ3tq5Xg9BieO3bbLcxSS3Hu56W6ldfW00V1SbzTHAOAIyYmx0sdrgN5rDtZdpOLstKuDSQlYs6QmrC7iRBDy7xDrSxmK50PgtwO8av793ZSkhv7Cuur3LegIeyxeEtfjMCkaURMufYEdTo0EDUeu+pcZpAX6FL7aNUzUOa5KnTEH2d3gLTXGPaTpGhJRs4OG39mQjsXkpDUvZRbhRZ/TJLMTcjoPuuEZ1zJht20j9rdUSkY6kZesQF2bkLOpuwcfHmbBnkKKE3qBfWCVYwAjoGi/5uIrGvdizPiHC+BPrrhnG9uMREadnm3StKdjgTIRK3qTnHZ5oeLLo7MlWlgnLpTdAK0uIdcmGxsY+MtxOVtsc4gjNpFK4lu1YEajlHCr2SwsNFp2u0i1oHRvpSjSZfyu+gHdGrSY5uMApNCVqGjx59Jlgl5IFpYWsz//fCiWSkqfdMkoPetaFgWeJMZ2OkgUOiMt9cPFNIA97h8J8WQBiS3Ymt+RJDWFX8R8g3uD8DmMS4IeNzy3CexqtFGfSMXyFBt34mv5pbpTbMi4rnzEs2DFUe1IOyAUApmdOpRN18znA+6mxNn5mCHAflLHYCOiuM4hco74msit7cj8HQnujCoJja4jU
    username: AgDMiO3hBIp65hkhwvquT6qDi3gxLjtnaU9Dqoc9fpGG8OwkwAwjr63a7WOAuA0hMEpAVBSq9PKe8bn0hc9tBtiM+pJwuzzJCtOvG3ez2K0ylJSrJkO9MFx1C/ASNSsc2XZLh4x46d5lTUUMe7cvZZ2pLJLJBBxCdmN+3jDzhle8/FNQdROQ2CAIiu7jQHm5XkIIH6abqNabsqfUEQ4W3mqTWN0YYEE2dnZxTjh5x4kIwqaZsbAFsRWouskSPoJEgzNlda2JPjTpiEOHzAXvXs2w1aj/x5eg1FzZ8wkXhC/RGt6C7p96HdZtS2dIsbkPfVUSt+rgcAxDt5wnnq3+0hRW13nAZMXzyU9HrqQO/6QAV/deqOR0TJBWn4G6IT1ZdTQDcc3kslKS7HOqAdsodqnoH+pNuy+AZVXrqJfq5/VcsOM+RcRcmU3V5Z+0t5ToP8QTaFt65rXucBvgdqBBLd10rMPZkJlYczco17WqYgVDI/MVmvl4+AuR8i7j2k7Cn3tIssx/qWjviybtnlX7DnBshrQIBbjMXEagCoh8L4XYVV0pvcKmZuxAbPrRmR1z4Nc3aBd4m0j7s+mlTvV4SQ7I4m2AOElkHuZLc/Vfk65UnoYEr0Zu5+pGxAlZzVm9du57kxexSDtypQ+a4s2/zuo0ygAvnh4Fp17WodHUpZEfpNWKGXpKnzd/qg9/nhnrnlujunxbbA==
  template:
    metadata:
      creationTimestamp: null
      name: database-secret
      namespace: default
    type: Opaque
---
